name: PluginTemplate
version: 1.0
description: This is a template.
author: nickguletskii200
authors: [nickguletskii200, JohnDoe]
main: org.nickguletskii200.PluginTemplate.PluginTemplate
database: false